### ISSUE TITLE
Player takes no knockback

### ISSUE THREAD

**Issue by BIoxyest** [Meldexun/EntityDesyncFix#1]
Not much else to say, just that the player takes absolutely no knockback from mobs when this mod is installed.

**Comment by Meldexun** [comment]
Works fine for me with only EntityDesyncFix installed.

**Comment by BIoxyest** [comment]
> Works fine for me with only EntityDesyncFix installed.

Weird, I made a vanilla Forge Minecraft installation with just this mod installed like you said, and I was still getting no knockback.
Removing this mod lets me get knockbacked again like normal.
I'm using Forge 14.23.5.2860 from MultiMC with MixinBootstrap-1.1.0.
[debug.log](https://github.com/Meldexun/EntityDesyncFix/files/8809266/debug.log)
[latest.log](https://github.com/Meldexun/EntityDesyncFix/files/8809268/latest.log)

**Comment by Meldexun** [comment]
Now I was able to reproduce the issue.
Fixed in v1.12.2-1.0.1
