### ISSUE TITLE
Actually Additions Worm Invisible

### ISSUE THREAD

**Issue by reddvilzz** [Meldexun/EntityDesyncFix#3]
**Describe the bug**

**To Reproduce**
1. Place Actually Additions Worms, Worms will turn invisible
2. Exit the World
3. Worm Reappear
4. I think there's nothing in the log, but I'm gonna go and test this to see if there's any log showing up.

**Versions**
Entity Desync Fix: 1.0.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Actually Additions 1.12.2-r152

**Comment by Meldexun** [comment]
Fixed in v1.12.2-1.0.2
